name: Manually Deploy to Heroku

on: workflow_dispatch

  # You may pin to the exact commit or the version.
  # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
jobs: 
   deploy:
    runs-on: ubuntu-latest
    steps:
       - uses: CDNievas/heroku-action@v1.0
         with:
    # Used for authentication. You can find it in your heroku homepage account settings
           heroku_api_key: 303d5c66-d5de-4b22-82b5-b36ed80227d1
    # Email from Heroku Account
           heroku_email: storage@fovies.tk
    # The appname to use for deploying/updating
           heroku_app_name: coderxleech
